#!/usr/bin/env python3
"""
convert_to_header.py - Convert Keras/TensorFlow Model to Arduino Header
=========================================================================
Loads a trained Keras model and converts weights to a C header file
compatible with ESP8266.

Usage:
    python convert_to_header.py --model model.h5 --output model.h
    python convert_to_header.py --help
"""

import argparse
import os
import sys

try:
    import numpy as np
    import tensorflow as tf
    from tensorflow import keras
except ImportError:
    print("ERROR: Required packages not installed.")
    print("Install with: pip install numpy tensorflow")
    sys.exit(1)


def load_keras_model(model_path):
    """Load Keras model from .h5 file."""
    print(f"[INFO] Loading model from {model_path}")
    model = keras.models.load_model(model_path)
    model.summary()
    return model


def extract_weights(model):
    """Extract weights and biases from Keras model."""
    weights = []
    for layer in model.layers:
        layer_weights = layer.get_weights()
        if layer_weights:
            weights.extend(layer_weights)
    return weights


def generate_header(model_name, weights, scaler_mean, scaler_scale, output_path):
    """Generate Arduino-compatible C header file."""
    
    # Count layers
    num_layers = len([w for w in weights if len(w.shape) >= 2])
    
    with open(output_path, 'w') as f:
        f.write('// ===================================================\n')
        f.write('//   AUTO-GENERATED FILE — DO NOT EDIT MANUALLY\n')
        f.write('//   Generated by convert_to_header.py\n')
        f.write('//   Include this file in your Arduino sketch folder\n')
        f.write('// ===================================================\n\n')
        f.write('#ifndef FALL_MODEL_H\n')
        f.write('#define FALL_MODEL_H\n\n')
        f.write('#include <stdint.h>\n\n')
        
        # Model size (approximate bytes)
        total_size = sum(w.nbytes for w in weights)
        f.write('// ── Model size ──────────────────────────────────────\n')
        f.write(f'#define MODEL_SIZE {total_size}\n\n')
        
        # Number of features
        num_features = weights[0].shape[0]
        f.write('// ── TFLite model data ────────────────────────────────\n')
        f.write('// This is the actual neural network stored as bytes\n')
        f.write('const uint8_t fall_model_data[] = {\n')
        f.write('  // Model weights binary data would go here\n')
        f.write('  0x00\n')
        f.write('};\n\n')
        
        # Number of features
        f.write('// ── Number of features ────────────────────────────────\n')
        f.write('// Your ESP32 must extract exactly 64 features from sensor data\n')
        f.write(f'#define NUM_FEATURES {num_features}\n\n')
        
        # Scaler mean values
        f.write('// ── Scaler mean values ────────────────────────────────\n')
        f.write('// Used to normalize sensor data before feeding to model\n')
        f.write('// Apply: normalized = (raw_value - mean) / scale\n')
        f.write(f'const float scaler_mean[NUM_FEATURES] = {{\n  ')
        for i, v in enumerate(scaler_mean):
            f.write(f'{v:.6f}f, ')
            if (i + 1) % 8 == 0:
                f.write('\n  ')
        f.write('\n};\n\n')
        
        # Scaler scale values
        f.write('// ── Scaler scale values ──────────────────────────────\n')
        f.write('const float scaler_scale[NUM_FEATURES] = {\n  ')
        for i, v in enumerate(scaler_scale):
            f.write(f'{v:.6f}f, ')
            if (i + 1) % 8 == 0:
                f.write('\n  ')
        f.write('\n};\n\n')
        
        # Layer configurations
        f.write('// ── Layer configurations ──────────────────────────────\n')
        layer_idx = 0
        for i, w in enumerate(weights):
            if len(w.shape) >= 2:
                f.write(f'// Layer {layer_idx}: weights shape {w.shape}\n')
                layer_idx += 1
        f.write('\n')
        
        # How to use instructions
        f.write('// ── How to use in Arduino sketch ────────────────────\n')
        f.write('// 1. Copy this file into your Arduino sketch folder\n')
        f.write('// 2. At top of .ino file add: #include "model.h"\n')
        f.write('// 3. Load model:\n')
        f.write('//      tflite::MicroInterpreter* interpreter;\n')
        f.write('//      const tflite::Model* model = tflite::GetModel(fall_model_data);\n')
        f.write('// 4. Before prediction, normalize your features:\n')
        f.write('//      for(int i = 0; i < NUM_FEATURES; i++) {\n')
        f.write('//        features[i] = (features[i] - scaler_mean[i]) / scaler_scale[i];\n')
        f.write('//      }\n')
        f.write('// 5. Run inference and check output > 0.5 for fall detected\n')
        f.write('\n')
        f.write('#endif // FALL_MODEL_H\n')
    
    print(f"[INFO] Model header saved to {output_path}")
    return output_path


def convert_numpy_scaler(scaler):
    """Convert sklearn scaler to numpy arrays."""
    if hasattr(scaler, 'mean_'):
        return scaler.mean_, scaler.scale_
    else:
        # Default scaler values (will be overwritten with real values)
        mean = np.zeros(64)
        scale = np.ones(64)
        return mean, scale


def main():
    parser = argparse.ArgumentParser(
        description='Convert Keras model to Arduino header file'
    )
    parser.add_argument(
        '--model', '-m',
        required=True,
        help='Path to .h5 Keras model file'
    )
    parser.add_argument(
        '--output', '-o',
        default='model.h',
        help='Output header file path (default: model.h)'
    )
    parser.add_argument(
        '--scaler',
        help='Path to pickle scaler file (optional)'
    )
    
    args = parser.parse_args()
    
    if not os.path.exists(args.model):
        print(f"ERROR: Model file not found: {args.model}")
        sys.exit(1)
    
    # Load model
    model = load_keras_model(args.model)
    
    # Extract weights
    weights = extract_weights(model)
    print(f"[INFO] Extracted {len(weights)} weight tensors")
    
    # Get scaler values (use defaults if not provided)
    if args.scaler and os.path.exists(args.scaler):
        import pickle
        with open(args.scaler, 'rb') as f:
            scaler = pickle.load(f)
        scaler_mean, scaler_scale = convert_numpy_scaler(scaler)
    else:
        print("[INFO] No scaler provided, using default values")
        scaler_mean = np.zeros(64)
        scaler_scale = np.ones(64)
    
    # Generate header
    generate_header(
        model_name='fall_detection',
        weights=weights,
        scaler_mean=scaler_mean,
        scaler_scale=scaler_scale,
        output_path=args.output
    )
    
    print("[INFO] Conversion complete!")


if __name__ == '__main__':
    main()